# USE ONLY WHEN THE OPTION COMPILE_WITH_OLD_ARCHITECTURE IS SET TO FALSE.
# https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/CMakeLists.txt
# NOTE: The smaller the priority number is, the higher the module priority is.
/**:
  ros__parameters:
    # NOTE: modules which are not set true in the preset is ignored in the slot configuration
    slots:
      # NOTE: array of array is not supported
      - slot1
      - slot2
      - slot3
      - slot4
    slot1:
      - "start_planner"
    slot2:
      - "side_shift"
      - "avoidance_by_lane_change"
      - "static_obstacle_avoidance"
      - "lane_change_left"
      - "lane_change_right"
      - "external_request_lane_change_left"
      - "external_request_lane_change_right"
    slot3:
      - "goal_planner"
    slot4:
      - "dynamic_obstacle_avoidance"

    external_request_lane_change_left:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: true

    external_request_lane_change_right:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: true

    lane_change_left:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true

    lane_change_right:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true

    start_planner:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: false

    side_shift:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false

    goal_planner:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: false

    static_obstacle_avoidance:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: false

    avoidance_by_lane_change:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false

    dynamic_obstacle_avoidance:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true

    sampling_planner:
      enable_module: true
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
