# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

# https://pre-commit.ci/#configuration
ci:
  autofix_commit_msg: "style(pre-commit-optional): autofix"
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: "ci(pre-commit-optional): quarterly autoupdate"

repos:
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.2
    hooks:
      - id: markdown-link-check
        args: [--quiet, --config=.markdown-link-check.json]
