language:
  - generic
cache:
  - apt
matrix:
  include:
    - dist: xenial
      compiler: gcc
      os: linux
      sudo: required
      env: ROS_DISTRO=kinetic
    - dist: xenial
      os: linux
      sudo: required
      services:
        - docker
      env: ROS_DISTRO=kinetic CROSS_COMPILE=1
    - dist: trusty
      compiler: gcc
      os: linux
      sudo: required
      env: ROS_DISTRO=indigo
notifications:
    slack: star4:911NA0lU8gDHitCKLto9LzPJ
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)
    - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

# Install system dependencies, and Autoware pre requisites (non-ros)
before_install:
  - if [ "${CROSS_COMPILE}" != "1" ]; then
      sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list";
      sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116;
      sudo apt-get update;
      sudo apt-get install -y  python-catkin-pkg python-rosdep python-wstool ros-${ROS_DISTRO}-catkin;
      source /opt/ros/${ROS_DISTRO}/setup.bash;
      sudo rosdep init;
      rosdep update;
    fi

# Install all ros dependencies, using wstool first and rosdep second.
# wstool looks for a ROSINSTALL_FILE defined in the environment variables.
before_script:
  - if [ "${CROSS_COMPILE}" != "1" ]; then
      cd ros/src;
      wstool init;
      test -f "${ROSINSTALL_FILE}" && wstool merge "${ROSINSTALL_FILE}";
      wstool up;
      cd ..;
      rosdep install -y --from-paths src --ignore-src --rosdistro ${ROS_DISTRO};
    fi

# Compile and test (mark the build as failed if any step fails). If the
# CATKIN_OPTIONS file exists, use it as an argument to catkin_make, for example
# to blacklist certain packages.
#
# NOTE on testing: `catkin_make run_tests` will show the output of the tests
# (gtest, nosetest, etc..) but always returns 0 (success) even if a test
# fails. Running `catkin_test_results` aggregates all the results and returns
# non-zero when a test fails (which notifies Travis the build failed).
script:
  - if [ "${CROSS_COMPILE}" == "1" ]; then
      docker run
        --rm
        -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}
        -w ${TRAVIS_BUILD_DIR}/ros
        esteve/autoware-kinetic:crossbuild-aarch64
        bash
          -c "source /opt/ros/kinetic/setup.bash &&
              catkin_make
                -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/ros/cross_toolchain.cmake
                -DCMAKE_SYSTEM_PROCESSOR=aarch64 clean &&
              source devel/setup.bash &&
              catkin_make
                -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/ros/cross_toolchain.cmake
                -DCMAKE_SYSTEM_PROCESSOR=aarch64 -j4";
    else
      catkin_make clean;
      source devel/setup.bash;
      catkin_make -j4;
    fi

#sudo: required
#dist: trusty
#language: generic
#compiler:
#  - gcc
#notifications:
#    slack: star4:911NA0lU8gDHitCKLto9LzPJ
#env:
#  matrix:
#    - USE_DEB=true  ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
##    - USE_DEB=true  ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
#    - USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
##    - USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
#install:
#  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
#script:
#  - source .ci_config/travis.sh
