/**:
  ros__parameters:
    # Ego path calculation
    use_predicted_trajectory: true
    use_imu_path: true
    use_pointcloud_data: true
    use_predicted_object_data: false
    use_object_velocity_calculation: true
    check_autoware_state: true
    min_generated_path_length: 0.5
    imu_prediction_time_horizon: 1.5
    imu_prediction_time_interval: 0.1
    mpc_prediction_time_horizon: 4.5
    mpc_prediction_time_interval: 0.1

    # Debug
    publish_debug_pointcloud: false
    publish_debug_markers: true

    # Point cloud partitioning
    detection_range_min_height: 0.0
    detection_range_max_height_margin: 0.0
    voxel_grid_x: 0.05
    voxel_grid_y: 0.05
    voxel_grid_z: 100000.0

    # Point cloud cropping
    expand_width: 0.1
    path_footprint_extra_margin: 4.0

    # Point cloud clustering
    cluster_tolerance: 0.15 #[m]
    cluster_minimum_height: 0.1
    minimum_cluster_size: 10
    maximum_cluster_size: 10000

    # RSS distance collision check
    longitudinal_offset: 2.0
    t_response: 1.0
    a_ego_min: -3.0
    a_obj_min: -1.0
    collision_keeping_sec: 2.0
    previous_obstacle_keep_time: 1.0
    aeb_hz: 10.0
