- name: Install cuDNN and TensorRT
  become: true
  ansible.builtin.apt:
    name:
      - "{{ 'libcudnn9-cuda-12=' + cudnn_version if ansible_architecture == 'aarch64' else 'libcudnn8=' + cudnn_version }}"
      - libnvinfer10={{ tensorrt_version }}
      - libnvinfer-plugin10={{ tensorrt_version }}
      - libnvonnxparsers10={{ tensorrt_version }}
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: true

- name: Install cuDNN and TensorRT Dev
  become: true
  ansible.builtin.apt:
    name:
      - "{{ 'libcudnn9-dev-cuda-12=' + cudnn_version if ansible_architecture == 'aarch64' else 'libcudnn8-dev=' + cudnn_version }}"
      - libnvinfer-dev={{ tensorrt_version }}
      - libnvinfer-plugin-dev={{ tensorrt_version }}
      - libnvinfer-headers-dev={{ tensorrt_version }}
      - libnvinfer-headers-plugin-dev={{ tensorrt_version }}
      - libnvonnxparsers-dev={{ tensorrt_version }}
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: true
  when: install_devel == 'y'

# apt-mark hold
- name: Prevent CUDA-related packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ 'libcudnn9-cuda-12' if ansible_architecture == 'aarch64' else 'libcudnn8' }}"
    - libcudnn8
    - libnvinfer10
    - libnvinfer-plugin10
    - libnvonnxparsers10

- name: Prevent CUDA-related Dev packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ 'libcudnn9-dev-cuda-12' if ansible_architecture == 'aarch64' else 'libcudnn8-dev' }}"
    - libnvinfer-dev
    - libnvinfer-plugin-dev
    - libnvinfer-headers-dev
    - libnvinfer-headers-plugin-dev
    - libnvonnxparsers-dev
  when: install_devel == 'y'
