/**:
  ros__parameters:
    module_list:
      - "blind_spot"
      - "crosswalk"
      - "detection_area"
      - "intersection"
      - "no_stopping_area"
      - "traffic_light"
      - "lane_change_left"
      - "lane_change_right"
      - "avoidance_left"
      - "avoidance_right"
      - "goal_planner"
      - "pull_out"
      - "intersection_occlusion"

    default_enable_list:
      - "blind_spot"
      - "crosswalk"
      - "detection_area"
      - "intersection"
      - "no_stopping_area"
      - "traffic_light"
      - "lane_change_left"
      - "lane_change_right"
      - "avoidance_left"
      - "avoidance_right"
      - "goal_planner"
      - "pull_out"
      - "intersection_occlusion"
