/**:
  ros__parameters:
    # Vehicle reference frame
    base_frame: "base_link"

    # Subscriber queue size
    input_sensor_points_queue_size: 1

    # NDT implementation type
    # 0=PCL_GENERIC, 1=PCL_MODIFIED, 2=OMP
    ndt_implement_type: 2

    # The maximum difference between two consecutive
    # transformations in order to consider convergence
    trans_epsilon: 0.01

    # The newton line search maximum step length
    step_size: 0.1

    # The ND voxel grid resolution
    resolution: 2.0

    # The number of iterations required to calculate alignment
    max_iterations: 30

    # Converged param type
    # 0=TRANSFORM_PROBABILITY, 1=NEAREST_VOXEL_TRANSFORMATION_LIKELIHOOD
    # NEAREST_VOXEL_TRANSFORMATION_LIKELIHOOD is only available when NDTImplementType::OMP is selected
    converged_param_type: 1

    # If converged_param_type is 0
    # Threshold for deciding whether to trust the estimation result
    converged_param_transform_probability: 3.0

    # If converged_param_type is 1
    # Threshold for deciding whether to trust the estimation result
    converged_param_nearest_voxel_transformation_likelihood: 2.3

    # The number of particles to estimate initial pose
    initial_estimate_particles_num: 100

    # Tolerance of timestamp difference between initial_pose and sensor pointcloud. [sec]
    initial_pose_timeout_sec: 1.0

    # Tolerance of distance difference between two initial poses used for linear interpolation. [m]
    initial_pose_distance_tolerance_m: 10.0

    # neighborhood search method in OMP
    # 0=KDTREE, 1=DIRECT26, 2=DIRECT7, 3=DIRECT1
    omp_neighborhood_search_method: 0

    # Number of threads used for parallel computing
    omp_num_threads: 4

    # The covariance of output pose
    output_pose_covariance:
      [
        0.025, 0.0,   0.0,   0.0,      0.0,      0.0,
        0.0,   0.025, 0.0,   0.0,      0.0,      0.0,
        0.0,   0.0,   0.025, 0.0,      0.0,      0.0,
        0.0,   0.0,   0.0,   0.000625, 0.0,      0.0,
        0.0,   0.0,   0.0,   0.0,      0.000625, 0.0,
        0.0,   0.0,   0.0,   0.0,      0.0,      0.000625,
      ]
