/**:
  ros__parameters:
    verbose: false
    max_iteration_num: 100
    traffic_light_signal_timeout: 1.0
    planning_hz: 10.0
    backward_path_length: 5.0
    forward_path_length: 300.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_length_buffer_for_end_of_pull_out: 5.0
    minimum_pull_over_length: 16.0

    refine_goal_search_radius_range: 7.5

    # parameters for turn signal decider
    turn_signal_intersection_search_distance: 30.0
    turn_signal_intersection_angle_threshold_deg: 15.0
    turn_signal_minimum_search_distance: 10.0
    turn_signal_search_time: 3.0
    turn_signal_shift_length_threshold: 0.3
    turn_signal_on_swerving: true

    enable_akima_spline_first: false
    enable_cog_on_centerline: false
    input_path_interval: 2.0
    output_path_interval: 2.0

    lane_following:
      drivable_area_right_bound_offset: 0.0
      drivable_area_left_bound_offset: 0.0
      drivable_area_types_to_skip: [road_border]

    closest_lanelet:
      distance_threshold: 5.0 # [m]
      yaw_threshold: 0.79 # [rad]
