# USE ONLY WHEN THE OPTION COMPILE_WITH_OLD_ARCHITECTURE IS SET TO FALSE.
# https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/CMakeLists.txt
# NOTE: The smaller the priority number is, the higher the module priority is.
/**:
  ros__parameters:
    external_request_lane_change_left:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 6
      max_module_size: 1

    external_request_lane_change_right:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 6
      max_module_size: 1

    lane_change_left:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 5
      max_module_size: 1

    lane_change_right:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 5
      max_module_size: 1

    start_planner:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 0
      max_module_size: 1

    side_shift:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 2
      max_module_size: 1

    goal_planner:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: true
      priority: 1
      max_module_size: 1

    avoidance:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 4
      max_module_size: 1

    avoidance_by_lc:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 3
      max_module_size: 1

    dynamic_avoidance:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 7
      max_module_size: 1
