- name: Autoware development environment
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Print configuration
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
      tags: [always]

  roles:
    # --- Base ---
    - role: autoware.dev_env.rmw_implementation
      tags: [rmw]
      vars:
        rmw_implementation__rosdistro: "{{ rosdistro }}"
        rmw_implementation__name: "{{ rmw_implementation }}"
