/**:
  ros__parameters:
    dynamic_avoidance:
      # avoidance is performed for the object type with true
      target_object:
        car: true
        truck: true
        bus: true
        trailer: true
        unknown: false
        bicycle: false
        motorcycle: true
        pedestrian: false

        min_obstacle_vel: 1.0 # [m/s]

      drivable_area_generation:
        lat_offset_from_obstacle: 0.8 # [m]
        time_to_avoid: 5.0 # [s]
        max_lat_offset_to_avoid: 1.0 # [m]
