/**:
  ros__parameters:
    distance_threshold: 0.5
    use_dynamic_map_loading: true
    timer_interval_ms: 100
    map_update_distance_threshold: 10.0
    map_loader_radius: 150.0
    publish_debug_pcd: False
