- name: Uninstall old versions
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: true

- name: Install dependencies for setting up apt sources
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
- name: Authorize Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Save result of 'dpkg --print-architecture'
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Save result of 'lsb_release -cs'
  ansible.builtin.command: lsb_release -cs
  register: lsb_release
  changed_when: false

# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: Add Docker apt repository to source list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    filename: docker
    state: present
    update_cache: true

- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

# sudo groupadd docker
- name: Add docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

# sudo usermod -aG docker $USER
- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Authorize NVIDIA Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey

- name: Save result of '. /etc/os-release;echo $ID$VERSION_ID'
  ansible.builtin.shell: . /etc/os-release;echo $ID$VERSION_ID
  register: distribution
  changed_when: false

- name: Save result of 'curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list'
  ansible.builtin.uri:
    url: https://nvidia.github.io/nvidia-docker/{{ distribution.stdout }}/nvidia-docker.list
    return_content: true
  register: nvidia_docker_list

# curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
- name: Add NVIDIA Docker apt repository to source list
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    content: "{{ nvidia_docker_list.content }}"
    mode: 0644

- name: Install NVIDIA Container Toolkit
  become: true
  ansible.builtin.apt:
    name:
      - nvidia-docker2
    update_cache: true

- name: Install Docker Compose
  become: true
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    force: true
    mode: 0775

- name: Install rocker
  become: true
  ansible.builtin.pip:
    name: rocker
    state: latest
    executable: pip3
