/**:
  ros__parameters:
    start_planner:
      th_arrived_distance: 1.0
      th_stopped_velocity: 0.01
      th_stopped_time: 1.0
      collision_check_margin: 1.0
      collision_check_distance_from_end: 1.0
      th_moving_object_velocity: 1.0
      # shift pull out
      enable_shift_pull_out: true
      check_shift_path_lane_departure: false
      minimum_shift_pull_out_distance: 0.0
      deceleration_interval: 15.0
      lateral_jerk: 0.5
      lateral_acceleration_sampling_num: 3
      minimum_lateral_acc: 0.15
      maximum_lateral_acc: 0.5
      maximum_curvature: 0.07
      # geometric pull out
      enable_geometric_pull_out: true
      divide_pull_out_path: false
      geometric_pull_out_velocity: 1.0
      arc_path_interval: 1.0
      lane_departure_margin: 0.2
      backward_velocity: -1.0
      pull_out_max_steer_angle: 0.26  # 15deg
      # search start pose backward
      enable_back: true
      search_priority: "efficient_path"  # "efficient_path" or "short_back_distance"
      max_back_distance: 30.0
      backward_search_resolution: 2.0
      backward_path_update_duration: 3.0
      ignore_distance_from_lane_end: 15.0
      # turns signal
      th_turn_signal_on_lateral_offset: 1.0
      intersection_search_length: 30.0
      length_ratio_for_turn_signal_deactivation_near_intersection: 0.5
      # freespace planner
      freespace_planner:
        enable_freespace_planner: true
        end_pose_search_start_distance: 20.0
        end_pose_search_end_distance: 30.0
        end_pose_search_interval: 2.0
        freespace_planner_algorithm: "astar"  # options: astar, rrtstar
        velocity: 1.0
        vehicle_shape_margin: 1.0
        time_limit: 3000.0
        minimum_turning_radius: 5.0
        maximum_turning_radius: 5.0
        turning_radius_size: 1
        # search configs
        search_configs:
          theta_size: 144
          angle_goal_range: 6.0
          curve_weight: 1.2
          reverse_weight: 1.0
          lateral_goal_range: 0.5
          longitudinal_goal_range: 2.0
        # costmap configs
        costmap_configs:
          obstacle_threshold: 30
        # -- A* search Configurations --
        astar:
          only_behind_solutions: false
          use_back: false
          distance_heuristic_weight: 1.0
        # -- RRT* search Configurations --
        rrtstar:
          enable_update: true
          use_informed_sampling: true
          max_planning_time: 150.0
          neighbor_radius: 8.0
          margin: 1.0
