# see AvoidanceParameters description in avoidance_module_data.hpp for description.
/**:
  ros__parameters:
    avoidance:
      resample_interval_for_planning: 0.3               # [m]
      resample_interval_for_output: 4.0                 # [m]
      detection_area_right_expand_dist: 0.0             # [m]
      detection_area_left_expand_dist: 1.0              # [m]
      drivable_area_right_bound_offset: 0.0             # [m]
      drivable_area_left_bound_offset: 0.0              # [m]

      # avoidance module common setting
      enable_bound_clipping: false
      enable_update_path_when_object_is_gone: false
      enable_force_avoidance_for_stopped_vehicle: false
      enable_safety_check: true
      enable_yield_maneuver: true
      enable_yield_maneuver_during_shifting: false
      disable_path_update: false

      # drivable area setting
      use_adjacent_lane: true
      use_opposite_lane: true
      use_intersection_areas: false
      use_hatched_road_markings: false

      # for debug
      publish_debug_marker: false
      print_debug_info: false

      # avoidance is performed for the object type with true
      target_object:
        car:
          is_target: true                              # [-]
          moving_speed_threshold: 1.0                  # [m/s]
          moving_time_threshold: 1.0                   # [s]
          max_expand_ratio: 0.0                        # [-]
          envelope_buffer_margin: 0.3                  # [m]
          avoid_margin_lateral: 1.0                    # [m]
          safety_buffer_lateral: 0.7                   # [m]
          safety_buffer_longitudinal: 0.0              # [m]
        truck:
          is_target: true
          moving_speed_threshold: 1.0
          moving_time_threshold: 1.0
          max_expand_ratio: 0.0
          envelope_buffer_margin: 0.3
          avoid_margin_lateral: 1.0
          safety_buffer_lateral: 0.7
          safety_buffer_longitudinal: 0.0
        bus:
          is_target: true
          moving_speed_threshold: 1.0
          moving_time_threshold: 1.0
          max_expand_ratio: 0.0
          envelope_buffer_margin: 0.3
          avoid_margin_lateral: 1.0
          safety_buffer_lateral: 0.7
          safety_buffer_longitudinal: 0.0
        trailer:
          is_target: true
          moving_speed_threshold: 1.0
          moving_time_threshold: 1.0
          max_expand_ratio: 0.0
          envelope_buffer_margin: 0.3
          avoid_margin_lateral: 1.0
          safety_buffer_lateral: 0.7
          safety_buffer_longitudinal: 0.0
        unknown:
          is_target: false
          moving_speed_threshold: 1.0
          moving_time_threshold: 1.0
          max_expand_ratio: 0.0
          envelope_buffer_margin: 0.3
          avoid_margin_lateral: 1.0
          safety_buffer_lateral: 0.7
          safety_buffer_longitudinal: 0.0
        bicycle:
          is_target: false
          moving_speed_threshold: 1.0
          moving_time_threshold: 1.0
          max_expand_ratio: 0.0
          envelope_buffer_margin: 0.8
          avoid_margin_lateral: 1.0
          safety_buffer_lateral: 1.0
          safety_buffer_longitudinal: 1.0
        motorcycle:
          is_target: false
          moving_speed_threshold: 1.0
          moving_time_threshold: 1.0
          max_expand_ratio: 0.0
          envelope_buffer_margin: 0.8
          avoid_margin_lateral: 1.0
          safety_buffer_lateral: 1.0
          safety_buffer_longitudinal: 1.0
        pedestrian:
          is_target: false
          moving_speed_threshold: 1.0
          moving_time_threshold: 1.0
          max_expand_ratio: 0.0
          envelope_buffer_margin: 0.8
          avoid_margin_lateral: 1.0
          safety_buffer_lateral: 1.0
          safety_buffer_longitudinal: 1.0
        lower_distance_for_polygon_expansion: 30.0      # [m]
        upper_distance_for_polygon_expansion: 100.0     # [m]

      # For target object filtering
      target_filtering:
        # params for avoidance of not-parked objects
        threshold_time_force_avoidance_for_stopped_vehicle: 10.0    # [s]
        object_ignore_section_traffic_light_in_front_distance: 30.0 # [m]
        object_ignore_section_crosswalk_in_front_distance: 30.0     # [m]
        object_ignore_section_crosswalk_behind_distance: 30.0       # [m]
        # detection range
        object_check_forward_distance: 150.0            # [m]
        object_check_backward_distance: 2.0             # [m]
        object_check_goal_distance: 20.0                # [m]
        # filtering parking objects
        threshold_distance_object_is_on_center: 1.0     # [m]
        object_check_shiftable_ratio: 0.6               # [-]
        object_check_min_road_shoulder_width: 0.5       # [m]
        # lost object compensation
        object_last_seen_threshold: 2.0

      # For safety check
      safety_check:
        safety_check_backward_distance: 100.0            # [m]
        safety_check_time_horizon: 10.0                  # [s]
        safety_check_idling_time: 1.5                    # [s]
        safety_check_accel_for_rss: 2.5                  # [m/ss]
        safety_check_hysteresis_factor: 2.0              # [-]
        safety_check_ego_offset: 1.0                     # [m]

      # For avoidance maneuver
      avoidance:
        # avoidance lateral parameters
        lateral:
          lateral_execution_threshold: 0.499            # [m]
          lateral_small_shift_threshold: 0.101          # [m]
          road_shoulder_safety_margin: 0.3              # [m]
          max_right_shift_length: 5.0
          max_left_shift_length: 5.0
        # avoidance distance parameters
        longitudinal:
          prepare_time: 2.0                             # [s]
          min_prepare_distance: 1.0                     # [m]
          min_slow_down_speed: 1.38                     # [m/s]
          buf_slow_down_speed: 0.56                     # [m/s]
          nominal_avoidance_speed: 8.33                 # [m/s]

      # For yield maneuver
      yield:
        yield_velocity: 2.78                            # [m/s]

      # For stop maneuver
      stop:
        max_distance: 20.0                              # [m]
        stop_buffer: 1.0                                # [m]

      constraints:
        # vehicle slows down under longitudinal constraints
        use_constraints_for_decel: false                # [-]

        # lateral constraints
        lateral:
          velocity: [1.0, 1.38, 11.1]                   # [m/s]
          max_accel_values: [0.5, 0.5, 0.5]             # [m/ss]
          min_jerk_values: [0.2, 0.2, 0.2]              # [m/sss]
          max_jerk_values: [1.0, 1.0, 1.0]             # [m/sss]

        # longitudinal constraints
        longitudinal:
          nominal_deceleration: -1.0                    # [m/ss]
          nominal_jerk: 0.5                             # [m/sss]
          max_deceleration: -2.0                        # [m/ss]
          max_jerk: 1.0                                 # [m/sss]
          max_acceleration: 1.0                         # [m/ss]

      target_velocity_matrix:
        col_size: 2
        matrix:
          [2.78, 13.9,                                  # velocity [m/s]
           0.50, 1.00]                                  # margin [m]

      shift_line_pipeline:
        trim:
          quantize_filter_threshold: 0.2
          same_grad_filter_1_threshold: 0.1
          same_grad_filter_2_threshold: 0.2
          same_grad_filter_3_threshold: 0.5
          sharp_shift_filter_threshold: 0.2
