/**:
  ros__parameters:
    control:
      type: diagnostic_aggregator/AnalyzerGroup
      path: control
      analyzers:
        control_command_gate:
          type: diagnostic_aggregator/AnalyzerGroup
          path: control_command_gate
          analyzers:
            node_alive_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: node_alive_monitoring
              analyzers:
                heartbeat:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: heartbeat
                  contains: ["vehicle_cmd_gate: heartbeat"]
                  timeout: 1.0

        autonomous_driving:
          type: diagnostic_aggregator/AnalyzerGroup
          path: autonomous_driving
          analyzers:
            node_alive_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: node_alive_monitoring
              analyzers:
                topic_status:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: topic_status
                  contains: [": control_topic_status"]
                  timeout: 1.0

            performance_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: performance_monitoring
              analyzers:
                lane_departure:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: lane_departure
                  contains: [": lane_departure"]
                  timeout: 1.0

                trajectory_deviation:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_deviation
                  contains: [": trajectory_deviation"]
                  timeout: 1.0

                control_state:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: control_state
                  contains: [": control_state"]
                  timeout: 1.0

        external_control:
          type: diagnostic_aggregator/AnalyzerGroup
          path: external_control
          analyzers:
            external_command_selector:
              type: diagnostic_aggregator/AnalyzerGroup
              path: external_command_selector
              analyzers:
                node_alive_monitoring:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: node_alive_monitoring
                  analyzers:
                    heartbeat:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: heartbeat
                      contains: ["external_cmd_selector: heartbeat"]
                      timeout: 1.0

            local_external_control:
              type: diagnostic_aggregator/AnalyzerGroup
              path: local_external_control
              analyzers:
                device_connection:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: device_connection
                  analyzers:
                    joy_controller_connection:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: joy_controller_connection
                      contains: [": joy_controller_connection"]
                      timeout: 1.0

            remote_external_control:
              type: diagnostic_aggregator/AnalyzerGroup
              path: remote_external_control
              analyzers:
                network_connection:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: network_connection
                  analyzers:
                    remote_control_topic_status:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: remote_control_topic_status
                      contains: [": remote_control_topic_status"]
                      timeout: 1.0
