/**:
  ros__parameters:
    localization:
      type: diagnostic_aggregator/AnalyzerGroup
      path: localization
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": localization_topic_status"]
              timeout: 1.0

        performance_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: performance_monitoring
          analyzers:
            matching_score:
              type: diagnostic_aggregator/GenericAnalyzer
              path: matching_score
              contains: ["ndt_scan_matcher"]
              timeout: 1.0

            localization_accuracy:
              type: diagnostic_aggregator/GenericAnalyzer
              path: localization_accuracy
              contains: ["localization: localization_error_monitor"]
              timeout: 1.0

            localization_stability:
              type: diagnostic_aggregator/GenericAnalyzer
              path: localization_stability
              contains: ["localization: pose_instability_detector"]
              timeout: 1.0

            # This diagnostic should ideally be avoided in terms of Fault Tree Analysis (FTA) compatibility.
            # However, we may need this since the localization accuracy is still not reliable enough and may produce
            # false positives. Thus, NOTE that this diagnostic should be removed in the future when the localization accuracy
            # is reliable enough.
            sensor_fusion_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: sensor_fusion_status
              contains: ["localization: ekf_localizer"]
              timeout: 1.0
