/**:
  ros__parameters:
    system:
      type: diagnostic_aggregator/AnalyzerGroup
      path: system
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": system_topic_status"]
              timeout: 1.0

        emergency_stop_operation:
          type: diagnostic_aggregator/GenericAnalyzer
          path: emergency_stop_operation
          contains: [": emergency_stop_operation"]
          timeout: 1.0

        resource_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: resource_monitoring
          analyzers:
            clock:
              type: diagnostic_aggregator/AnalyzerGroup
              path: clock
              analyzers:
                clock_offset:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: clock_offset
                  contains: [": NTP Offset"]
                  timeout: 10.0

            cpu:
              type: diagnostic_aggregator/AnalyzerGroup
              path: cpu
              analyzers:
                temperature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: temperature
                  contains: [": CPU Temperature"]
                  timeout: 3.0

                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": CPU Usage"]
                  timeout: 3.0

                thermal_throttling:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: thermal_throttling
                  contains: [": CPU Thermal Throttling"]
                  timeout: 3.0

                frequency:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: frequency
                  contains: [": CPU Frequency"]
                  timeout: 3.0

                load_average:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: load_average
                  contains: [": CPU Load Average"]
                  timeout: 3.0

            gpu:
              type: diagnostic_aggregator/AnalyzerGroup
              path: gpu
              analyzers:
                temperature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: temperature
                  contains: [": GPU Temperature"]
                  timeout: 3.0

                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: gpu_usage
                  contains: [": GPU Usage"]
                  timeout: 3.0

                memory_usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: memory_usage
                  contains: [": GPU Memory Usage"]
                  timeout: 3.0

                thermal_throttling:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: thermal_throttling
                  contains: [": GPU Thermal Throttling"]
                  timeout: 3.0

            memory:
              type: diagnostic_aggregator/AnalyzerGroup
              path: memory
              analyzers:
                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": Memory Usage"]
                  timeout: 3.0

            network:
              type: diagnostic_aggregator/AnalyzerGroup
              path: network
              analyzers:
                network_usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: network_usage
                  contains: [": Network Usage"]
                  timeout: 3.0

                network_traffic:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: network_traffic
                  contains: [": Network Traffic"]
                  timeout: 3.0

            storage:
              type: diagnostic_aggregator/AnalyzerGroup
              path: storage
              analyzers:
                temperature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: temperature
                  contains: [": HDD Temperature"]
                  timeout: 3.0

                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": HDD Usage"]
                  timeout: 3.0

                power_on_hours:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": HDD PowerOnHours"]
                  timeout: 3.0

                total_data_written:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": HDD TotalDataWritten"]
                  timeout: 3.0

            process:
              type: diagnostic_aggregator/AnalyzerGroup
              path: process
              analyzers:
                high_load:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: high_load
                  contains: [": High-load"]
                  timeout: 3.0

                high_mem:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: high_mem
                  contains: [": High-mem"]
                  timeout: 3.0

                tasks_summary:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: tasks_summary
                  contains: [": Tasks Summary"]
                  timeout: 3.0
