/**:
  ros__parameters:
    system:
      type: diagnostic_aggregator/AnalyzerGroup
      path: system
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": system_topic_status"]
              timeout: 1.0

        emergency_stop_operation:
          type: diagnostic_aggregator/GenericAnalyzer
          path: emergency_stop_operation
          contains: [": emergency_stop_operation"]
          timeout: 1.0

        service_log_checker:
          type: diagnostic_aggregator/GenericAnalyzer
          path: service_log_checker
          contains: ["service_log_checker"]
          timeout: 5.0

        duplicated_node_checker:
          type: diagnostic_aggregator/GenericAnalyzer
          path: duplicated_node_checker
          contains: ["duplicated_node_checker"]
          timeout: 5.0

        resource_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: resource_monitoring
          analyzers:
            clock:
              type: diagnostic_aggregator/AnalyzerGroup
              path: clock
              analyzers:
                clock_offset:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: clock_offset
                  contains: [": NTP Offset"]
                  timeout: 10.0

            cpu:
              type: diagnostic_aggregator/AnalyzerGroup
              path: cpu
              analyzers:
                temperature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: temperature
                  contains: [": CPU Temperature"]
                  timeout: 3.0

                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": CPU Usage"]
                  timeout: 3.0

                thermal_throttling:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: thermal_throttling
                  contains: [": CPU Thermal Throttling"]
                  timeout: 3.0

                frequency:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: frequency
                  contains: [": CPU Frequency"]
                  timeout: 3.0

                load_average:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: load_average
                  contains: [": CPU Load Average"]
                  timeout: 3.0

            gpu:
              type: diagnostic_aggregator/AnalyzerGroup
              path: gpu
              analyzers:
                temperature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: temperature
                  contains: [": GPU Temperature"]
                  timeout: 3.0

                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: gpu_usage
                  contains: [": GPU Usage"]
                  timeout: 3.0

                memory_usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: memory_usage
                  contains: [": GPU Memory Usage"]
                  timeout: 3.0

                thermal_throttling:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: thermal_throttling
                  contains: [": GPU Thermal Throttling"]
                  timeout: 3.0

                frequency:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: frequency
                  contains: [": GPU Frequency"]
                  timeout: 3.0

            memory:
              type: diagnostic_aggregator/AnalyzerGroup
              path: memory
              analyzers:
                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": Memory Usage"]
                  timeout: 3.0

            network:
              type: diagnostic_aggregator/AnalyzerGroup
              path: network
              analyzers:
                network_usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: network_usage
                  contains: [": Network Usage"]
                  timeout: 3.0

                network_traffic:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: network_traffic
                  contains: [": Network Traffic"]
                  timeout: 3.0

                network_crc_error:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: network_crc_error
                  contains: [": Network CRC Error"]
                  timeout: 3.0

                ip_packet_reassembles_failed:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: ip_packet_reassembles_failed
                  contains: [": IP Packet Reassembles Failed"]
                  timeout: 3.0

            storage:
              type: diagnostic_aggregator/AnalyzerGroup
              path: storage
              analyzers:
                temperature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: temperature
                  contains: [": HDD Temperature"]
                  timeout: 3.0

                recovered_error:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: recovered_error
                  contains: [": HDD RecoveredError"]
                  timeout: 3.0

                read_data_rate:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: read_data_rate
                  contains: [": HDD ReadDataRate"]
                  timeout: 3.0

                write_data_rate:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: write_data_rate
                  contains: [": HDD WriteDataRate"]
                  timeout: 3.0

                read_iops:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: read_iops
                  contains: [": HDD ReadIOPS"]
                  timeout: 3.0

                write_iops:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: write_iops
                  contains: [": HDD WriteIOPS"]
                  timeout: 3.0

                usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: usage
                  contains: [": HDD Usage"]
                  timeout: 3.0

                power_on_hours:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: power_on_hours
                  contains: [": HDD PowerOnHours"]
                  timeout: 3.0

                total_data_written:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: total_data_written
                  contains: [": HDD TotalDataWritten"]
                  timeout: 3.0

                connection:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: connection
                  contains: [": HDD Connection"]
                  timeout: 3.0

            process:
              type: diagnostic_aggregator/AnalyzerGroup
              path: process
              analyzers:
                high_load:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: high_load
                  contains: [": High-load"]
                  timeout: 3.0

                high_mem:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: high_mem
                  contains: [": High-mem"]
                  timeout: 3.0

                tasks_summary:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: tasks_summary
                  contains: [": Tasks Summary"]
                  timeout: 3.0

            hardware:
              type: diagnostic_aggregator/AnalyzerGroup
              path: voltage
              analyzers:
                cmos_battery:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: cmos_battery
                  contains: [": CMOS Battery Status"]
                  timeout: 3.0
