name: autoware-base

on:
  push:
    branches:
      - main
    paths:
      - .github/actions/docker-build-and-push-base
      - .github/workflows/autoware-base.yaml
      - amd64.env
      - ansible-galaxy-requirements.yaml
      - ansible/playbooks/openadkit.yaml
      - ansible/roles/**
      - arm64.env
      - docker/Dockerfile.base
      - docker/etc
      - docker/scripts/cleanup_*.sh
      - setup-dev-env.sh
  schedule:
    - cron: 0 0 15 * * # every 15th of the month
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autoware-base:
    strategy:
      matrix:
        platform: [humble, jazzy]
        include:
          - platform: humble
            runner: ubuntu-22.04
            env-file: amd64.env
            suffix: "" # no suffix for humble since it is default
            set-latest: true
          - platform: jazzy
            runner: ubuntu-24.04
            env-file: amd64_jazzy.env
            suffix: -jazzy
            set-latest: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with: # cSpell:ignore tonistiigi, binfmt
          image: tonistiigi/binfmt:qemu-v7.0.0

      - name: Load env file
        id: load-env
        uses: falti/dotenv-action@v1
        with:
          path: ${{ matrix.env-file }}
          export-variables: true
          log-variables: true

      - name: Build Autoware's base images
        uses: ./.github/actions/docker-build-and-push-base
        with:
          target-image: autoware-base
          build-args: |
            *.platform=linux/amd64,linux/arm64
            *.args.ROS_DISTRO=${{ steps.load-env.outputs.rosdistro }}
            *.args.BASE_IMAGE=${{ steps.load-env.outputs.base_image }}
          suffix: ${{ matrix.suffix }}
          set-latest: ${{ matrix.set-latest }}
