name: autoware-base

on:
  schedule:
    - cron: 0 0 15 * * # every 15th of the month
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build-and-push-base:
    needs: load-env
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Autoware's base images
        uses: ./.github/actions/docker-build-and-push-base
        with:
          target-image: autoware-base
          build-args: |
            *.platform=linux/amd64,linux/arm64
            *.args.ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            *.args.BASE_IMAGE=${{ needs.load-env.outputs.base_image }}
