name: build-and-test-differential

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  prevent-no-label-execution:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/prevent-no-label-execution.yaml@v1
    with:
      label: run-build-and-test-differential

  start-runner:
    name: Start self-hosted EC2 runner
    needs: prevent-no-label-execution
    if: ${{ needs.prevent-no-label-execution.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EC2_ON_DEMAND_AWS_ACCESS_KEY_ID_COMMON }}
          aws-secret-access-key: ${{ secrets.EC2_ON_DEMAND_AWS_SECRET_ACCESS_KEY_COMMON }}
          aws-region: ${{ secrets.EC2_ON_DEMAND_AWS_REGION_COMMON }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN_MFC }}
          ec2-image-id: ami-092a175a6ad1aad7a
          ec2-instance-type: c6a.xlarge
          subnet-id: subnet-070b3d46464230127
          security-group-id: sg-0cca5762919221f16
          runner-home-dir: /home/ubuntu/actions-runner

  build-and-test-differential:
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    container: ${{ matrix.container }}${{ matrix.container-suffix }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        container-suffix:
          - ""
          - -cuda
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware-universe:humble-latest
            build-depends-repos: build_depends.repos
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Build
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Test
        id: test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
          flags: differential

  clang-tidy-differential:
    needs: build-and-test-differential
    runs-on: ${{ needs.start-runner.outputs.label }}
    container: ghcr.io/autowarefoundation/autoware-universe:humble-latest-cuda
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Get modified files
        id: get-modified-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.cpp
            **/*.hpp

      - name: Run clang-tidy
        if: ${{ steps.get-modified-files.outputs.all_changed_files != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          target-files: ${{ steps.get-modified-files.outputs.all_changed_files }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy
          build-depends-repos: build_depends.repos

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - clang-tidy-differential
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EC2_ON_DEMAND_AWS_ACCESS_KEY_ID_COMMON }}
          aws-secret-access-key: ${{ secrets.EC2_ON_DEMAND_AWS_SECRET_ACCESS_KEY_COMMON }}
          aws-region: ${{ secrets.EC2_ON_DEMAND_AWS_REGION_COMMON }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN_MFC }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
