name: build-and-test-differential

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  prevent-no-label-execution:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/prevent-no-label-execution.yaml@v1
    with:
      label: tag:run-build-and-test-differential

  build-and-test-differential:
    needs: prevent-no-label-execution
    if: ${{ needs.prevent-no-label-execution.outputs.run == 'true' }}
    runs-on: [self-hosted, linux, X64]
    container: ${{ matrix.container }}${{ matrix.container-suffix }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        container-suffix:
          - ""
          - -cuda
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware-universe:humble-latest
            build-depends-repos: build_depends.repos
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check disk space before build
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Build
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Test
        id: test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
          flags: differential

      - name: Check disk space after build
        run: df -h

  clang-tidy-differential:
    runs-on: [self-hosted, linux, X64]
    container: ghcr.io/autowarefoundation/autoware-universe:humble-latest-cuda
    needs: build-and-test-differential
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Get modified files
        id: get-modified-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.cpp
            **/*.hpp

      - name: Run clang-tidy
        if: ${{ steps.get-modified-files.outputs.all_changed_files != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          target-files: ${{ steps.get-modified-files.outputs.all_changed_files }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy
          build-depends-repos: build_depends.repos
