name: build-and-test-scheduled

on:
  schedule:
    - cron: 0 19 * * * # run at 4 AM JST
  workflow_dispatch:

jobs:
  build-and-test-scheduled:
    runs-on: ${{ matrix.os }}
    container: ros:galactic
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ARM64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@tier4/proposal

      - name: Register AutonomouStuff repository
        uses: autowarefoundation/autoware-github-actions/register-autonomoustuff-repository@tier4/proposal
        with:
          rosdistro: galactic

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@tier4/proposal

      - name: Build and test
        uses: autowarefoundation/autoware-github-actions/colcon-build-and-test@tier4/proposal
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: build_depends.repos
