name: build-main

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      base-image: ${{ steps.set-env.outputs.base_image }}
      rosdistro: ${{ steps.set-env.outputs.rosdistro }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Set env
        run: |
          echo "base-image=${{ env.base_image }}" >> $GITHUB_OUTPUT
          echo "rosdistro=${{ env.rosdistro }}" >> $GITHUB_OUTPUT

  build-main:
    needs: load-env
    runs-on: ubuntu-latest
    container: ${{ needs.load-env.outputs.base-image }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.repos

      - name: Run vcs export
        run: |
          vcs export --exact src || true

      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro ${{ needs.load-env.outputs.rosdistro }}

      - name: Build
        run: |
          . /opt/ros/${{ needs.load-env.outputs.rosdistro }}/setup.sh
          colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release
