name: build-and-test

on:
  push:
  schedule:
    - cron: 0 19 * * * # run at 4 AM JST
  workflow_dispatch:

jobs:
  build-and-test:
    if: ${{ github.event_name != 'push' || github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@tier4/proposal

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@tier4/proposal

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@tier4/proposal
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: build_depends.repos

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@tier4/proposal
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: build_depends.repos

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
