name: build-humble-self-hosted

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  build-humble-self-hosted:
    runs-on: [self-hosted, linux, ARM64]
    container: ubuntu:22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: humble

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y universe

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.repos

      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro humble

      - name: Build
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release
