name: check-build-depends

on:
  pull_request:
    paths:
      - build_depends.repos

jobs:
  check-build-depends:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:galactic-latest-cuda
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Build
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: build_depends.repos
