name: clang-tidy-differential

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  make-sure-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:run-clang-tidy-differential

  clang-tidy-differential:
    needs: make-sure-label-is-present
    if: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware:latest-prebuilt-cuda
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Get modified files
        id: get-modified-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.cpp
            **/*.hpp

      - name: Run clang-tidy
        if: ${{ steps.get-modified-files.outputs.all_changed_files != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          target-files: ${{ steps.get-modified-files.outputs.all_changed_files }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy
          build-depends-repos: build_depends.repos

      - name: Show disk space after the tasks
        run: df -h
