name: deploy-docs

on:
  push:
    branches:
      - main
      - tier4/proposal
    paths:
      - mkdocs.yaml
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.jpg"
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

jobs:
  prevent-no-label-execution:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/prevent-no-label-execution.yaml@tier4/proposal
    with:
      label: documentation

  deploy-docs:
    needs: prevent-no-label-execution
    if: ${{ needs.prevent-no-label-execution.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Deploy docs
        uses: autowarefoundation/autoware-github-actions/deploy-docs@tier4/proposal
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
