name: docker-build-and-push-self-hosted

on:
  push:
    tags:
      - v*
  schedule:
    - cron: 0 0 1,15 * *
  workflow_dispatch:

jobs:
  docker-build-and-push-self-hosted:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      # https://github.com/actions/checkout/issues/211
      - name: Change permission of workspace
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Load env
        run: |
          cat amd64.env | sed "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed "/^#/d" >> $GITHUB_ENV
          fi

      - name: Build 'autoware-universe'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-universe
          build-args: |
            *.platform=linux/arm64
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.CUDA_IMAGE_TAG=${{ env.cuda_image_tag }}
            *.args.CUDNN_VERSION=${{ env.cudnn_version }}
            *.args.TENSORRT_VERSION=${{ env.tensorrt_version }}
          tag-suffix: -arm64

      - name: Show disk space
        run: |
          df -h
