name: docker-build-and-push-main-self-hosted

on:
  push:
    tags:
      - v*
      - "[0-9]+.[0-9]+*"
  schedule:
    - cron: 0 0 1,15 * *
  workflow_dispatch:

jobs:
  docker-build-and-push-main-self-hosted:
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
          - cuda
        include:
          - name: no-cuda
            base_image_env: base_image
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: cuda
            base_image_env: cuda_base_image
            setup-args: --no-cuda-drivers
            additional-tag-suffix: -cuda
    steps:
      # https://github.com/actions/checkout/issues/211
      - name: Change permission of workspace
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Build 'autoware-universe'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-universe
          build-args: |
            *.platform=linux/arm64
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.BASE_IMAGE=${{ env[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
          tag-prefix: ${{ env.rosdistro }}-
          tag-suffix: ${{ matrix.additional-tag-suffix }}-arm64

      - name: Show disk space
        run: |
          df -h
