name: docker-build-and-push-main

on:
  schedule:
    - cron: 0 0 1,15 * *
  workflow_dispatch:

jobs:
  docker-build-and-push-main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
        include:
          - name: no-cuda
            base_image_env: base_image
            setup-args: --no-nvidia
            additional-tag-suffix: ""
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Build 'autoware-universe'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-universe
          build-args: |
            *.platform=linux/amd64
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.BASE_IMAGE=${{ env[format('{0}', matrix.base_image_env)] }}
            *.args.PREBUILT_BASE_IMAGE=${{ env.prebuilt_base_image }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
          tag-prefix: ${{ env.rosdistro }}-
          tag-suffix: ${{ matrix.additional-tag-suffix }}-amd64

      - name: Show disk space
        run: |
          df -h
