# EVENTS: push, schedule, workflow_dispatch
# workflow_dispatch: Build all. No publish to registry; save as tarball.
# schedule: Build only devel and prebuilt. TAGS: date, latest
# push-branch: Build only devel and prebuilt. TAGS: date, latest
# push-tag: Build all. TAGS: version, date, latest

name: docker-build-and-push-main

on:
  push:
    tags:
      - adkit-v*.*.*
    branches:
      - main
  schedule:
    - cron: 0 0 1,15 * *
  workflow_dispatch:
    inputs:
      artifacts-destination:
        type: choice
        description: Destination for the artifacts
        options:
          - registry
          - tarball
        default: tarball

jobs:
  docker-build-and-push-main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
          - cuda
        include:
          - name: no-cuda
            base_image_env: base_image
            lib_dir: x86_64
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: cuda
            base_image_env: base_image
            lib_dir: x86_64
            additional-tag-suffix: -cuda
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Build 'Autoware'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware
          build-args: |
            *.platform=linux/amd64
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.BASE_IMAGE=${{ env[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
            *.args.LIB_DIR=${{ matrix.lib_dir }}
          tag-suffix: ${{ matrix.additional-tag-suffix }}
          tag-arch: amd64
          tag-prefix: ${{ env.rosdistro }}
          allow-push: true
      
      - name: Build 'Openadk'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-openadk
          build-args: |
            *.platform=linux/amd64
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.BASE_IMAGE=${{ env[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
            *.args.LIB_DIR=${{ matrix.lib_dir }}
          tag-suffix: ${{ matrix.additional-tag-suffix }}
          tag-arch: amd64
          tag-prefix: ${{ env.rosdistro }}
          allow-push: true

      - name: Show disk space
        run: |
          df -h
