name: generate-docs

on:
  push:
    branches:
      - main
      - tier4/proposal
    paths:
      - "mkdocs.yaml"
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.css"
  pull_request_target:
    paths:
      - "mkdocs.yaml"
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.css"

jobs:
  get-docs-version-name:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-get-docs-version-name.yaml@tier4/proposal

  generate-docs:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-generate-docs.yaml@tier4/proposal
    needs: get-docs-version-name
    with:
      script-ref: tier4/proposal
      mkdocs-yaml: mkdocs.yaml
      version-name: ${{ needs.get-docs-version-name.outputs.version-name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
