name: pre-commit-optional

on:
  pull_request:

jobs:
  pre-commit-optional:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run pre-commit
        uses: autowarefoundation/autoware-github-actions/pre-commit@v1
        with:
          pre-commit-config: .pre-commit-config-optional.yaml
          base-branch: origin/${{ github.base_ref }}
