name: pre-commit-ansible

on:
  pull_request:

jobs:
  pre-commit-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy depends for ansible-lint
        run: |
          ansible-galaxy collection install -f -r ansible-galaxy-requirements.yaml

      - name: Run pre-commit
        uses: autowarefoundation/autoware-github-actions/pre-commit@v1
        with:
          pre-commit-config: .pre-commit-config-ansible.yaml
