name: remove-old-pr-docs

on:
  pull_request_target:
    types:
      - closed

jobs:
  get-docs-version-name:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-get-docs-version-name.yaml@tier4/proposal

  remove-old-pr-docs:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-remove-docs.yaml@tier4/proposal
    needs: get-docs-version-name
    with:
      script-ref: tier4/proposal
      mkdocs-yaml: mkdocs.yaml
      version-name: ${{ needs.get-docs-version-name.outputs.version-name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
