name: setup-docker

on:
  pull_request:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  setup-docker:
    needs: load-env
    runs-on: ubuntu-latest
    container: ${{ needs.load-env.outputs.base-image }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y -v docker
