# Update submodules to nightly.
# .repos sync is not handled here (maybe run pre-commit once?)
name: Update Nightly Submodules

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:

jobs:
  update-nightly-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Update nightly submodules
        id: update-nightly-submodules
        env:
          MAIN_BRANCH_NAME: main
          NIGHTLY_BRANCH_NAME: nightly
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git checkout "${MAIN_BRANCH_NAME}"
          git checkout -B "${NIGHTLY_BRANCH_NAME}"

          # Check if repository has submodules
          if [ ! -f .gitmodules ]; then
            echo "Error: The repository is not using git submodules"
            exit 1
          fi

          git submodule update --init --checkout
          git submodule update --remote
          git add .
          git commit -m "chore: update nightly submodules from ${MAIN_BRANCH_NAME}" || echo "No submodule updates to commit"
          git push origin "${NIGHTLY_BRANCH_NAME}" --force-with-lease
