name: update-docker-manifest

on:
  schedule:
    - cron: 0 19 * * * # run at 4 AM JST
  workflow_dispatch:

jobs:
  update-docker-manifest:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: autoware-universe
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Create Docker manifest
        run: |
          package_full_name=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}

          url="https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ matrix.package-name }}/versions"

          echo "url: $url"
          tags=$(curl -fsSL "$url" -H "Authorization: token ${{ github.token }}" | jq ".[].metadata.container.tags[]" | cut -d '"' -f 2)

          amd64_tags=$(echo "$tags" | grep "\-amd64" | sed "s/-amd64$//g")
          arm64_tags=$(echo "$tags" | grep "\-arm64" | sed "s/-arm64$//g")
          base_tags=$(printf "%s\n" "$amd64_tags" "$arm64_tags" | sort | uniq)

          echo "amd64_tags: "$amd64_tags""
          echo "arm64_tags: "$arm64_tags""
          echo "base_tags: "$base_tags""

          for base_tag in $base_tags; do
            amd64_tag="$package_full_name":$(echo "$tags" | grep "$base_tag\-amd64")
            arm64_tag="$package_full_name":$(echo "$tags" | grep "$base_tag\-arm64")

            echo "base_tag: $base_tag"
            echo "amd64_tag: $amd64_tag"
            echo "arm64_tag: $arm64_tag"

            docker manifest create $package_full_name:$base_tag \
              $amd64_tag \
              $arm64_tag

            docker manifest push $package_full_name:$base_tag
          done
