name: update-docker-manifest

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-docker-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Combine multi arch images for 'autoware'
        uses: ./.github/actions/combine-multi-arch-images
        with:
          package-name: autoware

      - name: Combine multi arch images for 'openadkit'
        uses: ./.github/actions/combine-multi-arch-images
        with:
          package-name: autoware-openadkit
