name: vcs-import

on:
  pull_request:
  workflow_dispatch:

jobs:
  vcs-import:
    runs-on: ubuntu-latest
    container: ros:humble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pip for rosdep
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip

      - name: Register AutonomouStuff repository
        uses: autowarefoundation/autoware-github-actions/register-autonomoustuff-repository@v1
        with:
          rosdistro: humble

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.repos

      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro humble
